### ISSUE TITLE
Error creating oauth_token.json and credentials.json files

### ISSUE THREAD

**Issue by cvc90** [AfonsoFGarcia/hass-bluecon#2] opened 2024-02-10 20:48 UTC
Hello @AfonsoFGarcia 

as you can see in the attached image, it happens to me like [Should this project work?](https://github.com/AfonsoFGarcia/hass-bluecon/issues/1)

![image](https://github.com/AfonsoFGarcia/hass-bluecon/assets/76731844/e7f41c10-fc13-40d1-9121-853bf3aa2bdd)

The oauth_token.json, credentials.json and persistent_ids.txt files do not seem to be created properly as they are created but empty.

Could you put a copy of these files as a sample so I can create them manually?

Could you also indicate all the python libraries used that must be installed for a good performance?

In case it helps you, I have the Docker version, now running Home Assistant version core 2024.3.1

Attached image of the error log

![image](https://github.com/AfonsoFGarcia/hass-bluecon/assets/76731844/cc45a856-012c-471c-b997-71fb610e7e3f)
![image](https://github.com/AfonsoFGarcia/hass-bluecon/assets/76731844/6aa944be-a53b-4dff-a0da-916fac1e3529)

PD: the files have permissions 777

**Comment by swas** [comment] 2024-03-07 16:11
Same here :(

**Comment by AfonsoFGarcia** [comment] 2024-09-12 22:33
Closing as duplicate of #1 which is already solved.

**Closed by AfonsoFGarcia** 2024-09-12 22:33 UTC
